### ISSUE TITLE
Windows Installation doesn't work on W7

### ISSUE THREAD

**Issue by cptalpdeniz** [xorond/passtrust#1]
Tried to install it with the method written in install.md for windows and it gives me error when I try to execute "ruby passtrust".

C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:
15:in `rescue in <module:Windows>': Could not load the required ffi gem, install
 it with: gem install ffi (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:12:in`module:Windows'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:4:in `<module:Clipboard>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:3:in`<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in`const_get'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in `implementation'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:55:in`<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:91:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:91:in`block (2 levels) in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:86:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:86:in`block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in`require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler.r
b:106:in `require'
        from passtrust:4:in`<main>'

**Comment by xorond** [comment]
It looks like the ffi gem was not installed while installing the clipboard gem (I would need to investigate why).
Try `gem install ffi` and see if that fixes the issue for you.

**Comment by cptalpdeniz** [comment]
Installed ffi and same error.

**Comment by xorond** [comment]
https://github.com/xorond/passtrust/commit/9721caec84fc33f3688f3e0259d8a86d14d0c560

Try `git pull` to take in the latest change (or just re-download the zip file) and try the installation instructions again please.

**Comment by cptalpdeniz** [comment]
I don't know why but even after installing ffi and new version, it still gives me the error "Could not load the required ffi gem..."

Error log:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboard/windows.rb:
15:in `rescue in <module:Windows>': Could not load the required ffi gem, install
 it with: gem install ffi (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:12:in`module:Windows'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:4:in `<module:Clipboard>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d/windows.rb:3:in`<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in`const_get'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:32:in `implementation'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/clipboard-1.1.1/lib/clipboar
d.rb:55:in`<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:91:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:91:in`block (2 levels) in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:86:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:86:in`block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler/r
untime.rb:75:in`require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.1/lib/bundler.r
b:106:in `require'
        from passtrust:4:in`<main>'

**Comment by xorond** [comment]
I just pushed out some changes to make the clipboard and ffi gems optional dependencies.
https://github.com/xorond/passtrust/commit/470d0ff65831824b52cf265cae52d4317da3ccb1
Try running `bundle install --without optional` after pulling in the latest changes.
It seemed to work without those gems in my testing, however you will not be able to use the clipboard functionalities (at least until this is resolved in a more permanent way).

**Comment by cptalpdeniz** [comment]
It works! Thanks for solving the issue. Have a great day.

**Comment by xorond** [comment]
Thanks for reporting. This issue will be closed.
